# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b58b7f45f4208ade49ff365c2fb40d1573e95134879cc09bc93760e947506688f1589663a3fe6a2e313b520144f347906cefb57a6c2e60276271755d03f0d0

test:
  secret_key_base: 33bf04700444ae2473c0fa97a44fa16aa23b4b45609448220d6855a353a9b8b7af33c18829f8555d08ff74703acc028c810bd358957bc113fc55c780ec1df010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
